Repository starplanter93/The_Garden_of_Musicsheet, pull requests merged in 2023-02, with the labels that each got.

#27 Feat: 이미지 레이아웃 atom 구현, text scss 파일 일부 수정
  client/src/assets/default-image.jpg
  client/src/components/UI/atoms/ImgLayout/ImgLayout.stories.tsx
  client/src/components/UI/atoms/ImgLayout/ImgLayout.tsx
  client/src/components/UI/atoms/ImgLayout/imglayout.module.scss
  client/src/components/UI/atoms/Text/Text.stories.tsx
  client/src/components/UI/atoms/Text/Text.tsx
  client/src/components/UI/atoms/Text/text.module.scss
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/atoms/text/text.module.scss
Labels: Feat, Design, Refactor

#25 Refactor: scss 모듈화에 따른 클래스명 간소화
  client/src/components/UI/atoms/Icon/Icon.tsx
  client/src/components/UI/atoms/Icon/icon.module.scss
  client/src/utils/_utils.scss
Labels: Design, Refactor

#29 Feat: Button Atom 구현
  client/src/components/UI/atoms/Button/Button.stories.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Button/button.module.scss
  client/src/components/UI/atoms/index.ts
Labels: Feat, Design, Test

#31 Feat: InstrumentCard Molecule 구현
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.scss
  client/src/App.tsx
  client/src/components/UI/atoms/ImgLayout/ImgLayout.tsx
  client/src/components/UI/atoms/ImgLayout/imglayout.module.scss
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.stories.tsx
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.tsx
  client/src/components/UI/molecules/InstrumentCard/instrumentCard.module.scss
  client/src/components/UI/molecules/index.ts
Labels: Feat, Design, Refactor, Test, Setting

#35 Feat: CategoryCover Molecule 구현
  client/src/components/UI/molecules/CategoryCover/CategoryCover.stories.tsx
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
  client/src/components/UI/molecules/index.ts
Labels: Feat, Design, Test

#37 Refactor: CategoryCover artist가 있는 경우 표시하도록 수정
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
Labels: Refactor

#38 Feat: 메인페이지 곡 타이틀, 악보리스트 molecule 작성, storybook CI 설정추가
  .github/workflows/chromatic.yml
  client/.gitignore
  client/build-storybook.log
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/molecules/MainScoreList/MainScoreList.stories.tsx
  client/src/components/UI/molecules/MainScoreList/MainScoreList.tsx
  client/src/components/UI/molecules/MainScoreList/mainscorelist.module.scss
  client/src/components/UI/molecules/SongTitle/SongTitle.stories.tsx
  client/src/components/UI/molecules/SongTitle/SongTitle.tsx
  client/src/components/UI/molecules/SongTitle/songtitle.module.scss
  client/src/components/UI/molecules/index.ts
  client/src/components/pages/Test.tsx
  client/tsconfig.json
Labels: Feat, Design, Test, Setting

#39 Feat: 악기 페이지의 악기 리스트 Organism 구현
  client/src/components/UI/molecules/InstrumentCard/instrumentCard.module.scss
  client/src/components/UI/organisms/InstrumentLists/InstrumentLists.stories.tsx
  client/src/components/UI/organisms/InstrumentLists/InstrumentLists.tsx
  client/src/components/UI/organisms/InstrumentLists/instrumentLists.module.scss
  client/src/components/UI/organisms/index.ts
Labels: Feat, Design, Test

#43 Feat: Header Menu molecule 구현
  client/src/components/UI/molecules/GNB/Menu/Menu.stories.tsx
  client/src/components/UI/molecules/GNB/Menu/Menu.tsx
  client/src/components/UI/molecules/GNB/Menu/menu.module.scss
  client/src/components/UI/molecules/index.ts
Labels: Feat, Design, Test

#48 Feat: UserDropdown organism 구현
  client/src/components/UI/molecules/UserDropdown/MiniProfile/MiniProfile.stories.tsx
  client/src/components/UI/molecules/UserDropdown/MiniProfile/MiniProfile.tsx
  client/src/components/UI/molecules/UserDropdown/MiniProfile/miniProfile.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.stories.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/userMenu.module.scss
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/UserDropdown/UserDropdown.stories.tsx
  client/src/components/UI/organisms/UserDropdown/UserDropdown.tsx
  client/src/components/UI/organisms/UserDropdown/userDropdown.module.scss
  client/src/components/UI/organisms/index.ts
Labels: Feat, Design, Test

#51 Feat: Header organism 구현 및 Router 초기 셋팅
  client/src/App.tsx
  client/src/assets/Logo.png
  client/src/components/UI/atoms/Logo/Logo.stories.tsx
  client/src/components/UI/atoms/Logo/Logo.tsx
  client/src/components/UI/atoms/Logo/logo.module.scss
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/organisms/Header/Header.stories.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Layout/Layout.tsx
  client/src/components/pages/Layout/layout.module.scss
  client/src/components/pages/index.ts
  client/src/components/pages/page.ts
  client/src/index.scss
  client/src/index.tsx
Labels: Feat, Design, Test

#53 Feat: MainSongSection organism 구현
  client/src/App.tsx
  client/src/components/UI/molecules/MainScoreList/MainScoreList.tsx
  client/src/components/UI/molecules/MainScoreList/mainscorelist.module.scss
  client/src/components/UI/molecules/SongTitle/SongTitle.stories.tsx
  client/src/components/UI/molecules/SongTitle/SongTitle.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.stories.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/MainSongSection/mainsongsection.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Test.tsx
Labels: Feat, Design

#55 Feat: 회원가입, 로그인 organism 기능 구현
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/atoms/Icon/icons/index.ts
  client/src/components/UI/atoms/Input/Input.stories.tsx
  client/src/components/UI/atoms/Input/Input.tsx
  client/src/components/UI/atoms/Input/input.module.scss
  client/src/components/UI/atoms/Label/Label.stories.tsx
  client/src/components/UI/atoms/Label/Label.tsx
  client/src/components/UI/atoms/Label/label.scss
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/UserAuthInput/UserAuthInput.stories.tsx
  client/src/components/UI/molecules/UserAuthInput/UserAuthInput.tsx
  client/src/components/UI/molecules/UserAuthInput/userAuthInput.module.scss
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.stories.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/UserAuth/userAuth.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/firebase/firebase.jsx
  client/src/index.tsx
  client/src/redux/LoginSlice.tsx
  client/src/redux/RegSlice.tsx
  client/src/redux/UserSlice.tsx
  client/src/redux/store.ts
  client/src/utils/ApiCollection/User.tsx
  client/src/utils/Regex.tsx
  client/src/utils/utils.ts
Labels: Feat, Design, Test

#57 Feat: Carousel organism 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/album_img1.png
  client/src/assets/album_img2.png
  client/src/assets/album_img3.png
  client/src/assets/carouselImg.tsx
  client/src/assets/carousel_bg1.png
  client/src/assets/carousel_bg2.png
  client/src/assets/carousel_bg3.png
  client/src/components/UI/organisms/Carousel/Carousel.stories.tsx
  client/src/components/UI/organisms/Carousel/Carousel.tsx
  client/src/components/UI/organisms/Carousel/carousel.scss
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/pages/Test.tsx
Labels: Feat, Design

#61 Feat: 메인 메뉴 Link 연결 및 active 스타일 적용
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/components/UI/molecules/GNB/Menu/GlobalMenu.stories.tsx
  client/src/components/UI/molecules/GNB/Menu/GlobalMenu.tsx
  client/src/components/UI/molecules/GNB/Menu/globalmenu.module.scss
  client/src/components/UI/organisms/Header/Header.stories.tsx
Labels: Feat, Design, Refactor, Test

#62 Feat: 악기 페이지 구현
  client/.storybook/preview.js
  client/src/App.tsx
  client/src/components/UI/molecules/GNB/Menu/GlobalMenu.stories.tsx
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.stories.tsx
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.tsx
  client/src/components/UI/molecules/InstrumentCard/instrumentCard.module.scss
  client/src/components/UI/organisms/Header/Header.stories.tsx
  client/src/components/UI/organisms/InstrumentLists/InstrumentLists.stories.tsx
  client/src/components/UI/organisms/InstrumentLists/InstrumentLists.tsx
  client/src/components/UI/organisms/InstrumentLists/instrumentLists.module.scss
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/MainSongSection/mainsongsection.module.scss
  client/src/components/pages/Instrument/Instrument.stories.tsx
  client/src/components/pages/Instrument/Instrument.tsx
  client/src/components/pages/Instrument/instrument.module.scss
  client/src/components/pages/index.ts
Labels: Feat, Design, Test

#65 Feat: 파이어베이스 유저 정보 읽기 와 파이어베이스 DB 접근법 공유 및 구글 Oauth 구현
  client/src/App.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/UserAuth/userAuth.module.scss
  client/src/components/pages/PostMusic/PostMusic.module.scss
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/components/pages/index.ts
  client/src/firebase/firebase.jsx
  client/src/redux/UserSlice.tsx
  client/src/utils/ApiCollection/User.tsx
  client/src/utils/utils.ts
Labels: Feat, Design

#67 Feat: Header UI 분기 및 Dropdown 닫기 기능 구현
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/UserDropdown/UserDropdown.stories.tsx
  client/src/components/UI/organisms/UserDropdown/UserDropdown.tsx
  client/src/components/UI/organisms/UtilityMenu/UtilityMenu.tsx
  client/src/components/UI/organisms/UtilityMenu/utilityMenu.module.scss
  client/src/utils/localStorage.ts
Labels: Feat, Refactor, Test

#70 Feat: UserMenu 와 악보 등록페이지 라우팅 연결
  client/.gitignore
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/atoms/Input/Input.stories.tsx
  client/src/components/UI/atoms/Input/Input.tsx
  client/src/components/UI/atoms/Input/input.module.scss
  client/src/components/UI/molecules/PostInput/PostInput.stories.tsx
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostInput/postInput.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/MusicPostInfo/MusicPostInfo.stories.tsx
  client/src/components/UI/organisms/MusicPostInfo/MusicPostInfo.tsx
  client/src/components/UI/organisms/MusicPostInfo/musicPostInfo.module.scss
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/pages/PostMusic/PostMusic.module.scss
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/react-app-env.d.ts
  client/src/redux/HeaderSlice.tsx
  client/src/redux/store.ts
  client/src/utils/ApiCollection/SearchData.tsx
  client/src/utils/ApiCollection/User.tsx
Labels: Feat

#72 Feat: redux-persist 적용
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/molecules/GNB/UserButton/UserButton.tsx
  client/src/components/UI/molecules/UserDropdown/MiniProfile/MiniProfile.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/index.tsx
  client/src/redux/UserSlice.tsx
  client/src/redux/store.ts
Labels: Feat

#74 Feat: 메인페이지 동적렌더링
  client/src/components/UI/molecules/MainScoreList/mainscorelist.module.scss
  client/src/components/UI/organisms/MainGrid/MainGrid.stories.tsx
  client/src/components/UI/organisms/MainGrid/MainGrid.tsx
  client/src/components/UI/organisms/MainGrid/maingrid.module.scss
  client/src/components/UI/organisms/MainSongSection/MainSongSection.stories.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/pages/Main/Main.tsx
  client/src/components/pages/Test.tsx
  client/src/firebase/firebase.tsx
Labels: Feat

#73 Feat: 악보 등록페이지의 악보 정보 제작
  client/package-lock.json
  client/package.json
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Button/button.module.scss
  client/src/components/UI/atoms/Icon/icons/index.ts
  client/src/components/UI/atoms/Input/Input.tsx
  client/src/components/UI/atoms/Input/input.module.scss
  client/src/components/UI/atoms/Logo/logo.module.scss
  client/src/components/UI/molecules/DropDownSelect/DropDown.stories.tsx
  client/src/components/UI/molecules/DropDownSelect/DropDown.tsx
  client/src/components/UI/molecules/DropDownSelect/dropDown.module.scss
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostSidebar/PostSidebar.stories.tsx
  client/src/components/UI/molecules/PostSidebar/PostSidebar.tsx
  client/src/components/UI/molecules/PostSidebar/postSidebar.module.scss
  client/src/components/UI/molecules/TextEditor/TextEditor.stories.tsx
  client/src/components/UI/molecules/TextEditor/TextEditor.tsx
  client/src/components/UI/molecules/TextEditor/textEditor.module.scss
  client/src/components/UI/molecules/UserAuthInput/UserAuthInput.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/MusicPostInfo/Buttons/PostButtons.stories.tsx
  client/src/components/UI/organisms/MusicPostInfo/Buttons/PostButtons.tsx
  client/src/components/UI/organisms/MusicPostInfo/Buttons/postButtons.module.scss
  client/src/components/UI/organisms/MusicPostInfo/MusicPostInfo.tsx
  client/src/components/UI/organisms/MusicPostInfo/musicPostInfo.module.scss
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/UserAuth/userAuth.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Auth/Auth.module.scss
  client/src/components/pages/Instrument/Instrument.tsx
  client/src/components/pages/PostMusic/PostMusic.module.scss
  client/src/components/pages/PostMusic/PostMusic.stories.tsx
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
  client/src/redux/store.ts
Labels: Feat, Design

#78 Feat: 악기 상세페이지 및 구성 요소 구현
  client/src/App.tsx
  client/src/components/UI/molecules/EditOrDownButton/EditOrDownButton.stories.tsx
  client/src/components/UI/molecules/EditOrDownButton/EditOrDownButton.tsx
  client/src/components/UI/molecules/GNB/Menu/GlobalMenu.tsx
  client/src/components/UI/molecules/GNB/Menu/globalmenu.module.scss
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.stories.tsx
  client/src/components/UI/molecules/InstrumentCard/InstrumentCard.tsx
  client/src/components/UI/molecules/Pagination/Pagination.stories.tsx
  client/src/components/UI/molecules/Pagination/Pagination.tsx
  client/src/components/UI/molecules/Pagination/pagination.module.scss
  client/src/components/UI/molecules/ScoreList/ScoreList.stories.tsx
  client/src/components/UI/molecules/ScoreList/ScoreList.tsx
  client/src/components/UI/molecules/ScoreList/scoreList.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.module.scss
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.stories.tsx
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/InstrumentLists/InstrumentLists.tsx
  client/src/components/UI/organisms/InstrumentLists/instrumentDummy.ts
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/InstrumentDetail/InstrumentDetail.stories.tsx
  client/src/components/pages/InstrumentDetail/InstrumentDetail.tsx
  client/src/components/pages/index.ts
  client/src/firebase/firebase.tsx
  client/src/redux/UserSlice.tsx
  client/src/utils/ApiCollection/User.tsx
Labels: Feat, Design, Refactor, Test

#80 Feat: 악보 등록페이지 api 리펙토링
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostSidebar/PostSidebar.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/FileSlice.tsx
  client/src/redux/PostSlice.tsx
  client/src/redux/store.ts
Labels: Feat, Fix, Refactor

#81 Feat: User 컬렉션에 데이터 추가 연동 구현
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostSidebar/PostSidebar.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/MusicPostInfo/MusicPostInfo.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
Labels: Feat, Refactor

#82 Feat: 악보 상세 페이지 구현
  client/src/App.tsx
  client/src/components/UI/molecules/ScoerInfoExplain/ScoreInfoExplain.stories.tsx
  client/src/components/UI/molecules/ScoerInfoExplain/ScoreInfoExplain.tsx
  client/src/components/UI/molecules/ScoerInfoExplain/scoreinfoexplain.module.scss
  client/src/components/UI/molecules/ScoreInfoCard/ScoreInfoCard.stories.tsx
  client/src/components/UI/molecules/ScoreInfoCard/ScoreInfoCard.tsx
  client/src/components/UI/molecules/ScoreInfoCard/scoreinfocard.module.scss
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.stories.tsx
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.tsx
  client/src/components/UI/molecules/ScoreInfoHeader/scoreinfoheader.module.scss
  client/src/components/UI/molecules/ScorePreview/ScorePreview.stories.tsx
  client/src/components/UI/molecules/ScorePreview/ScorePreview.tsx
  client/src/components/UI/molecules/ScorePreview/scorepreview.module.scss
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.stories.tsx
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/components/UI/molecules/ScorePriceCard/scorepricecard.module.scss
  client/src/components/UI/molecules/UserCard/UserCard.stories.tsx
  client/src/components/UI/molecules/UserCard/UserCard.tsx
  client/src/components/UI/molecules/UserCard/usercard.module.scss
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/MainGrid/MainGrid.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/ScoreInfoAside/ScoreInfoAside.stories.tsx
  client/src/components/UI/organisms/ScoreInfoAside/ScoreInfoAside.tsx
  client/src/components/UI/organisms/ScoreInfoAside/scoreInfoAside.module.scss
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.stories.tsx
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.tsx
  client/src/components/UI/organisms/ScoreInfoMain/scoreInfoMain.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Main/Main.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.stories.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/components/pages/ScoreInfo/scoreInfo.module.scss
  client/src/components/pages/Test.tsx
  client/src/components/pages/index.ts
Labels: Feat, Design

#88 Feat: 악보 상세페이지 데이터 렌더링
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/molecules/MainScoreList/MainScoreList.tsx
  client/src/components/UI/molecules/ScoerInfoExplain/ScoreInfoExplain.tsx
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.stories.tsx
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.tsx
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/components/UI/organisms/MainGrid/MainGrid.stories.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.stories.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/ScoreInfoAside/scoreInfoAside.module.scss
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.stories.tsx
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.tsx
  client/src/components/pages/Main/Main.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/components/pages/Test.tsx
  client/src/firebase/firebase.tsx
Labels: Feat

#89 Refactor: 상세페이지 탭메뉴 및 페이지네이션 수정
  client/src/components/UI/molecules/Pagination/Pagination.tsx
  client/src/components/UI/molecules/ScoreList/ScoreList.tsx
  client/src/components/UI/molecules/TabMenu/TabMenu.tsx
  client/src/components/UI/molecules/TabMenu/tabMenu.module.scss
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.tsx
  client/src/components/pages/InstrumentDetail/InstrumentDetail.tsx
  client/src/components/pages/MusicDetail/MusicDetail.tsx
Labels: Feat, Design, Refactor

#93 Feat: 마이페이지 제작
  client/src/App.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Button/button.module.scss
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
  client/src/components/UI/molecules/EditOrDownButton/EditOrDownButton.tsx
  client/src/components/UI/molecules/OptOutModal/OptOutModal.stories.tsx
  client/src/components/UI/molecules/OptOutModal/OptOutModal.tsx
  client/src/components/UI/molecules/OptOutModal/optOutModal.module.scss
  client/src/components/UI/molecules/ScoreList/ScoreList.tsx
  client/src/components/UI/molecules/TextEditor/textEditor.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/organisms/MyPageTop/MyPageTop.stories.tsx
  client/src/components/UI/organisms/MyPageTop/MyPageTop.tsx
  client/src/components/UI/organisms/MyPageTop/myPageTop.module.scss
  client/src/components/UI/organisms/UserDropdown/UserDropdown.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/MyPage/MyPage.stories.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/components/pages/MyPage/myPage.module.scss
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/components/pages/index.ts
  client/src/firebase/firebase.tsx
  client/src/utils/Spinner/Spinner.tsx
  client/src/utils/Spinner/spinner.scss
Labels: Feat, Design

#94 Feat: 메인페이지 무한스크롤 구현
  client/src/components/UI/organisms/Carousel/Carousel.tsx
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.tsx
  client/src/components/UI/organisms/ScoreInfoMain/scoreInfoMain.module.scss
  client/src/components/pages/Main/Main.tsx
  client/src/components/pages/Main/main.module.scss
  client/src/components/pages/ScoreInfo/scoreInfo.module.scss
Labels: Feat, Design

#96 Feat: 헤더 Bad setState 이슈 및 포스트 레이아웃 제작
  client/src/App.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Icon/Icon.tsx
  client/src/components/UI/atoms/Input/Input.tsx
  client/src/components/UI/atoms/Text/Text.tsx
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostSidebar/PostSidebar.tsx
  client/src/components/UI/molecules/TextEditor/TextEditor.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/UI/organisms/PostHeader/postheader.module.scss
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Instrument/Instrument.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/components/pages/PostLayout/PostLayout.tsx
  client/src/components/pages/PostLayout/postlayout.module.scss
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/components/pages/index.ts
  client/src/firebase/firebase.tsx
  client/src/redux/HeaderSlice.tsx
  client/src/redux/store.ts
  client/src/utils/ApiCollection/User.tsx
Labels: Feat, Fix, Refactor

#98 Feat: 마이페이지 제작 및 기능 구현
  client/src/App.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
  client/src/components/UI/molecules/MyPageModal/MyPageModal.stories.tsx
  client/src/components/UI/molecules/MyPageModal/MyPageModal.tsx
  client/src/components/UI/molecules/MyPageModal/myPageModal.module.scss
  client/src/components/UI/molecules/OptOutModal/OptOutModal.stories.tsx
  client/src/components/UI/molecules/OptOutModal/OptOutModal.tsx
  client/src/components/UI/molecules/UserDropdown/MiniProfile/MiniProfile.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/MyPageTop/MyPageTop.tsx
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/UI/organisms/UserDropdown/UserDropdown.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
  client/src/redux/UserSlice.tsx
  client/src/utils/ApiCollection/User.tsx
Labels: Feat, Fix, Design, Refactor

#99 Feat: 수정 페이지 및 구성 컴포넌트 구현 등
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/atoms/Input/Input.tsx
  client/src/components/UI/atoms/Input/input.module.scss
  client/src/components/UI/atoms/LoadingSpinner/LoadingSpinner.stories.tsx
  client/src/components/UI/atoms/LoadingSpinner/LoadingSpinner.tsx
  client/src/components/UI/atoms/LoadingSpinner/loadingSpinner.module.scss
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/DropDownSelect/DropDown.tsx
  client/src/components/UI/molecules/DropDownSelect/dropDown.module.scss
  client/src/components/UI/molecules/EditOrDownButton/EditOrDownButton.tsx
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/molecules/PostInput/postInput.module.scss
  client/src/components/UI/molecules/PostSidebar/PostSidebar.tsx
  client/src/components/UI/molecules/PostSidebar/postSidebar.module.scss
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.tsx
  client/src/components/UI/molecules/ScoreList/ScoreList.tsx
  client/src/components/UI/molecules/TextEditor/TextEditor.tsx
  client/src/components/UI/molecules/TextEditor/textEditor.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/organisms/MusicPostInfo/Buttons/PostButtons.tsx
  client/src/components/UI/organisms/MusicPostInfo/Buttons/postButtons.module.scss
  client/src/components/UI/organisms/MusicPostInfo/MusicPostInfo.tsx
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/pages/EditScore/EditScore.stories.tsx
  client/src/components/pages/EditScore/EditScore.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/components/pages/PostMusic/PostMusic.module.scss
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/components/pages/index.ts
  client/src/firebase/firebase.tsx
Labels: Feat, Design, Refactor, Test

#101 Feat: Footer 구현
  client/src/components/UI/atoms/Icon/icons/index.ts
  client/src/components/UI/organisms/Footer/Footer.stories.tsx
  client/src/components/UI/organisms/Footer/Footer.tsx
  client/src/components/UI/organisms/Footer/footer.module.scss
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/Layout/Layout.stories.tsx
  client/src/components/pages/Layout/Layout.tsx
  client/src/components/pages/Layout/layout.module.scss
Labels: Feat, Design, Test

#104 Refactor: 메인페이지에서 마지막 데이터일 경우에 Footer가 보이도록 수정
  client/src/components/pages/Layout/Layout.tsx
  client/src/components/pages/Main/Main.tsx
  client/src/redux/FooterSlice.tsx
  client/src/redux/store.ts
Labels: Refactor

#105 Feat: 마이페이지 css 및 파이어베이스 호출 로직 수정
  client/src/components/UI/atoms/Logo/logo.module.scss
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/GNB/Menu/globalmenu.module.scss
  client/src/components/UI/molecules/MainScoreList/mainscorelist.module.scss
  client/src/components/UI/molecules/MyPageModal/MyPageModal.tsx
  client/src/components/UI/molecules/MyPageModal/myPageModal.module.scss
  client/src/components/UI/molecules/PostInput/PostInput.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/components/pages/MyPage/myPage.module.scss
  client/src/firebase/firebase.tsx
  client/src/redux/UserSlice.tsx
  client/src/utils/ApiCollection/SearchData.tsx
  client/src/utils/ApiCollection/User.tsx
Labels: Feat, Fix, Design, Refactor

#107 Feat: 게시글 삭제 구현
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
  client/src/components/UI/molecules/MyPageModal/MyPageModal.tsx
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.tsx
  client/src/components/UI/molecules/UserDropdown/UserMenu/UserMenu.tsx
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.tsx
  client/src/components/UI/organisms/MainGrid/MainGrid.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/MyPageTop/MyPageTop.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/pages/Instrument/Instrument.tsx
  client/src/components/pages/InstrumentDetail/InstrumentDetail.tsx
  client/src/components/pages/Main/Main.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/components/pages/PostMusic/PostMusic.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
  client/src/utils/ApiCollection/User.tsx
Labels: Feat, Fix, Refactor

#108 Feat: 장바구니 구현
  client/src/App.tsx
  client/src/components/UI/molecules/CartBody/CartBody.stories.tsx
  client/src/components/UI/molecules/CartBody/CartBody.tsx
  client/src/components/UI/molecules/CartBody/cartBody.module.scss
  client/src/components/UI/molecules/CartFooter/CartFooter.stories.tsx
  client/src/components/UI/molecules/CartFooter/CartFooter.tsx
  client/src/components/UI/molecules/CartFooter/cartFooter.module.scss
  client/src/components/UI/molecules/CartHeader/CartHeader.stories.tsx
  client/src/components/UI/molecules/CartHeader/CartHeader.tsx
  client/src/components/UI/molecules/CartHeader/cartHeader.module.scss
  client/src/components/UI/molecules/CartList/CartList.stories.tsx
  client/src/components/UI/molecules/CartList/CartList.tsx
  client/src/components/UI/molecules/CartList/cartList.module.scss
  client/src/components/UI/molecules/GNB/CartButton/CartButton.tsx
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/CartModal/CartModal.tsx
  client/src/components/UI/organisms/CartModal/cartModal.module.scss
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/UI/organisms/PostHeader/postheader.module.scss
  client/src/components/UI/organisms/ScoreInfoAside/ScoreInfoAside.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/components/pages/Test.tsx
  client/src/components/pages/test.module.scss
  client/src/firebase/firebase.tsx
  client/src/redux/ModalSlice.tsx
  client/src/redux/store.ts
Labels: Feat, Design
