Repository starplanter93/The_Garden_of_Musicsheet, pull requests merged in 2023-01, with the labels that each got.

#5 Setting: 프리즈마 , 스웨거 초기세팅 완료
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20230124084823_schema_test/migration.sql
  backend/prisma/migrations/migration_lock.toml
  backend/prisma/schema.prisma
  backend/src/auth/auth.module.ts
  backend/src/main.ts
  backend/src/post/post.module.ts
  backend/src/prisma.service.ts
Labels: Back

#9 Deploy : codedeploy 설정 파일
  backend/appspec.yml
Labels: Deploy

#15 Test: 스토리북 전역 스타일 설정
  client/.storybook/preview-head.html
  client/.storybook/preview.js
Labels: Test

#16 Feat: Text Atoms 구현
  client/src/components/UI/atoms/text/Text.stories.tsx
  client/src/components/UI/atoms/text/Text.tsx
  client/src/components/UI/atoms/text/text.scss
Labels: Feat, Design

#19 Feat: Icon Atom 구현
  client/src/components/UI/atoms/Icon/Icon.stories.tsx
  client/src/components/UI/atoms/Icon/Icon.tsx
  client/src/components/UI/atoms/Icon/icon.scss
  client/src/components/UI/atoms/Icon/icons/index.ts
  client/src/components/UI/atoms/index.ts
Labels: Feat, Design, Test

#18 devCICD yml파일 수정
  .github/workflows/devCICD.yml
Labels: Deploy, Setting

#24 Refactor: Text atom scss module로 변경 및 내부 코드 수정
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/atoms/text/Text.tsx
  client/src/components/UI/atoms/text/text.module.scss
  client/src/components/UI/atoms/text/text.scss
Labels: Refactor
