Repository starplanter93/The_Garden_of_Musicsheet, pull requests merged in 2023-03, with the labels that each got.

#110 Design: Header, Footer, Layout 모바일 반응형 구현
  client/src/components/UI/atoms/Logo/logo.module.scss
  client/src/components/UI/molecules/GNB/CartButton/cartButton.module.scss
  client/src/components/UI/molecules/GNB/Menu/globalmenu.module.scss
  client/src/components/UI/molecules/UserDropdown/MiniProfile/miniProfile.module.scss
  client/src/components/UI/molecules/UserDropdown/UserMenu/userMenu.module.scss
  client/src/components/UI/organisms/Footer/footer.module.scss
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/Header/header.module.scss
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/UI/organisms/PostHeader/postheader.module.scss
  client/src/components/UI/organisms/UserDropdown/userDropdown.module.scss
  client/src/components/UI/organisms/UtilityMenu/utilityMenu.module.scss
  client/src/components/pages/Layout/layout.module.scss
  client/src/components/pages/PostLayout/PostLayout.tsx
  client/src/components/pages/PostLayout/postlayout.module.scss
  client/src/index.scss
  client/src/utils/_utils.scss
Labels: Design

#112 Fix: 장바구니 이슈 해결
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
  client/src/firebase/firebase.tsx
Labels: Fix

#116 Feat: 비로그인 상태에서 장바구니 담기 버튼 비활성화
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/firebase/firebase.tsx
Labels: Feat

#117 Design: 악기 페이지 및 구성 컴포넌트 반응형 구현
  README.md
  client/src/components/UI/atoms/LoadingSpinner/loadingSpinner.module.scss
  client/src/components/UI/molecules/InstrumentCard/instrumentCard.module.scss
  client/src/components/UI/organisms/Footer/footer.module.scss
  client/src/components/UI/organisms/InstrumentLists/instrumentLists.module.scss
  client/src/components/pages/Instrument/instrument.module.scss
  client/src/utils/_utils.scss
Labels: Fix, Design, Refactor

#118 Feat: 탭 메뉴 로직 변경 및 악기 상세, 곡 상세페이지 모바일 반응형 구현
  client/src/components/UI/molecules/ScoreList/scoreList.module.scss
  client/src/components/UI/molecules/TabMenu/TabMenu.stories.tsx
  client/src/components/UI/molecules/TabMenu/TabMenu.tsx
  client/src/components/UI/molecules/TabMenu/tabMenu.module.scss
  client/src/components/UI/organisms/CartModal/CartModal.tsx
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.module.scss
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
Labels: Feat, Design, Refactor

#120 Design: ScoreInfo 페이지 반응형 구현
  client/src/components/UI/molecules/ScoreInfoCard/scoreinfocard.module.scss
  client/src/components/UI/molecules/ScoreInfoHeader/scoreinfoheader.module.scss
  client/src/components/UI/molecules/ScorePriceCard/scorepricecard.module.scss
  client/src/components/UI/organisms/ScoreInfoAside/scoreInfoAside.module.scss
  client/src/components/UI/organisms/ScoreInfoMain/ScoreInfoMain.tsx
  client/src/components/UI/organisms/ScoreInfoMain/scoreInfoMain.module.scss
  client/src/components/pages/ScoreInfo/scoreInfo.module.scss
Labels: Design

#121 Design: 메인페이지 반응형 구현
  client/src/components/UI/organisms/Carousel/carousel.scss
  client/src/components/UI/organisms/MainGrid/maingrid.module.scss
  client/src/components/UI/organisms/MainSongSection/mainsongsection.module.scss
Labels: Design

#123 Design: CartModal 반응형 구현
  client/src/components/UI/molecules/ScoreInfoCard/scoreinfocard.module.scss
  client/src/components/UI/organisms/CartModal/cartModal.module.scss
  client/src/components/UI/organisms/ScoreInfoAside/scoreInfoAside.module.scss
  client/src/components/UI/organisms/ScoreInfoMain/scoreInfoMain.module.scss
Labels: Design

#124 Design: userAuth, Mypage 반응형 추가
  client/src/components/UI/atoms/ImgLayout/ImgLayout.tsx
  client/src/components/UI/atoms/ImgLayout/imglayout.module.scss
  client/src/components/UI/atoms/Label/label.scss
  client/src/components/UI/molecules/CategoryCover/CategoryCover.tsx
  client/src/components/UI/molecules/CategoryCover/categoryCover.module.scss
  client/src/components/UI/molecules/Pagination/Pagination.tsx
  client/src/components/UI/molecules/UserAuthInput/userAuthInput.module.scss
  client/src/components/UI/molecules/UserDropdown/MiniProfile/MiniProfile.tsx
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/UI/organisms/UserAuth/UserAuth.tsx
  client/src/components/pages/MyPage/MyPage.tsx
  client/src/firebase/firebase.tsx
  client/src/redux/UserSlice.tsx
Labels: Design

#129 Feat: ScoreInfo 페이지에서 uid와 authorId가 일치할 때만 수정, 삭제 버튼이 노출되도록 로직추가
  client/src/components/UI/molecules/ScoreInfoHeader/ScoreInfoHeader.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
Labels: Feat

#132 Fix : 미사용 변수 제거
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
  client/src/components/pages/MyPage/MyPage.tsx
Labels: Fix

#135 Setting: Action에 .env 파일 생성 및 환경변수 설정
  .github/workflows/devCICD.yml
  .github/workflows/mainCICD.yml
Labels: Setting

#136 Setting: .env 파일 위치 변경
  .github/workflows/devCICD.yml
  .github/workflows/mainCICD.yml
Labels: Setting

#133 Fix: 장바구니 모달 관련 여러 이슈 수정
  client/src/components/UI/molecules/CartFooter/CartFooter.tsx
  client/src/components/UI/molecules/GNB/CartButton/CartButton.tsx
  client/src/components/UI/organisms/CartModal/cartModal.module.scss
Labels: Fix

#126 Fix: 여러가지 이슈 수정 및 Readme 수정
  README.md
  client/src/components/UI/atoms/ImgLayout/imglayout.module.scss
  client/src/components/UI/atoms/LoadingSpinner/LoadingSpinner.tsx
  client/src/components/UI/atoms/LoadingSpinner/loadingSpinner.module.scss
  client/src/components/UI/molecules/TabMenu/tabMenu.module.scss
  client/src/components/UI/organisms/Carousel/Carousel.tsx
  client/src/components/UI/organisms/MainGrid/MainGrid.tsx
  client/src/components/UI/organisms/MainSongSection/MainSongSection.tsx
  client/src/components/UI/organisms/PostHeader/PostHeader.tsx
Labels: Fix, Docs

#139 Fix : 게시글 작성 css 수정
  client/src/components/UI/molecules/PostInput/postInput.module.scss
  client/src/components/pages/PostMusic/PostMusic.module.scss
Labels: Fix

#141 Feat: uid와 authorId를 대조하여 장바구니 담기 버튼 분기 추가
  client/src/components/UI/molecules/ScorePriceCard/ScorePriceCard.tsx
  client/src/components/UI/organisms/CategoryDetail/CategoryDetail.tsx
  client/src/components/UI/organisms/ScoreInfoAside/ScoreInfoAside.tsx
  client/src/components/pages/ScoreInfo/ScoreInfo.tsx
Labels: Feat

#144 Setting: 배포 전 불필요 파일 삭제, NotFound페이지 추가, 이미지에 alt속성 추가, readme 수정
  README.md
  client/README.md
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/assets/asset.ts
  client/src/assets/notFound.png
  client/src/components/UI/organisms/Carousel/Carousel.tsx
  client/src/components/pages/NotFound/NotFound.stories.tsx
  client/src/components/pages/NotFound/NotFound.tsx
  client/src/components/pages/NotFound/notFound.module.scss
  client/src/components/pages/Test.tsx
  client/src/components/pages/index.ts
  client/src/components/pages/test.module.scss
  client/src/redux/action/action.ts
Labels: Feat, Fix, Docs, Setting

#145 Setting: Readme 내용 추가 및 favicon 적용, index.html 수정 등
  README.md
  client/public/favicon.ico
  client/public/index.html
  client/public/logo152.png
  client/public/manifest.json
Labels: Docs, Setting

#152 Fix: songId 필드 타입 변경
  README.md
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
Labels: Fix

#153 Deploy ver. 1.0.1
  client/build-storybook.log
  client/src/firebase/firebase.tsx
  client/src/redux/PostSlice.tsx
Labels: Deploy

#155 Fix: 헤더의 장바구니 버블 숫자 갱신 안되는 버그 수정
  client/src/components/UI/molecules/GNB/CartButton/CartButton.tsx
Labels: Fix
